apiVersion: v1
kind: Template
metadata:
  name: idmsvc
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: ${APP_NAME}
    spec:
      envName: ${ENV_NAME}
      title: "Directory & Domain Services"
      deploymentRepo: https://github.com/podengo-project/idmsvc-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/${APP_NAME}
      image: ${IMAGE}:${IMAGE_TAG}
      navItems: 
        - appId: "${APP_NAME}"
          title: "Directory & Domain Services"
          href: "/settings/${APP_NAME}"
          product: "Domain"
      module:
        manifestLocation: "/apps/${APP_NAME}/fed-mods.json"
        modules:
          - id: "${APP_NAME}"
            module: "./RootApp"
            routes: 
            - pathname: "/settings/${APP_NAME}"

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: TBD
  - name: APP_NAME
    value: idmsvc
