---
name: Validate

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: make lint
      - run: make test
